import { existsSync, readdirSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import type { Plugin } from "vite";

/**
 * THE EXPLOSIVE DEVICE — RAPPER'S OWN COPY.
 *
 * WHY A COPY AND NOT AN IMPORT. ReTreever carries the original at
 * src/lib/core/harnessGuards/noEscapePlugin.ts. rapper cannot import it: the
 * only path to it is `../ReTreever/...`, a raw climb into a parent repo that
 * exists on this machine and nowhere else — precisely the escape this file is
 * built to stop. A guard that breaks its own rule to be installed is not a
 * guard. So it is copied, on purpose, the same way cn.ts is copied into each
 * child that needs it.
 *
 * KEEP THE TWO IN STEP. They are byte-identical below this header as of
 * 25 Aug 2026. If you change the rule, change it in both — there is no build
 * step that will tell you, because there deliberately is no link between them.
 *
 * THE EXPLOSIVE DEVICE. A raw path may not leave the repo — only an alias may.
 *
 * WHY A VITE PLUGIN AND NOT A LINT RULE
 * A lint rule requires somebody to run the linter and to not silence the
 * warning. This is `vite build` itself: throw here and there is no bundle, so
 * there is nothing to deploy. Vercel runs this. It cannot be skipped, ignored,
 * or argued with, and no developer has to care for it to work.
 *
 * WHY resolveId AND NOT A REGEX OVER THE SOURCE
 * A regex inspects the blueprint; this stands at the door. Rollup calls
 * resolveId for EVERY import it actually resolves — in .svelte files, in CSS,
 * in template literals, in code generated by another plugin — and hands over
 * the resolved path and the importer as facts. There is no syntax to
 * anticipate and nothing to miss.
 *
 * THE RULE, EXACTLY
 *   - Inside the repo, `../` is ordinary. Not our business.
 *   - Leaving the repo is allowed ONLY through an alias ($harness, $lib …).
 *     An alias is a declared, reviewable seam; a raw `../../../` climb is not.
 *   - node_modules and virtual modules are exempt — that is how packages work.
 *
 * SECOND CHARGE: CASE.
 * macOS formats APFS case-INSENSITIVE, so `./assets/PUB-rtvr/x.webp` opens the
 * file that is really called `pub-Rtvr`. Vite resolves it, the page renders,
 * the build is green — and it dies on Linux, which is what Vercel builds on.
 * MEASURED 25 Aug 2026: wrong case → page 200 locally. A local "it works" is
 * not evidence when the dev filesystem is more permissive than the deploy one.
 * So the exact spelling is asserted against what readdir REPORTS, never
 * against whether the file opens — opening is the check that lies.
 */

/** Does this path exist with EXACTLY this spelling? */
function exactCase(abs: string): boolean {
	if (!existsSync(abs)) return false;
	let cur = resolve(sep);
	for (const seg of relative(sep, abs).split(sep)) {
		if (!seg) continue;
		let names: string[];
		try {
			names = readdirSync(cur);
		} catch {
			return true; // unreadable parent — not this plugin's business
		}
		if (!names.includes(seg)) return false;
		cur = join(cur, seg);
	}
	return true;
}

/**
 * Find the CHILD a file belongs to, if any.
 *
 * A child is a direct subfolder of the workspace holding a `lib/`. Walking up
 * from the file and stopping at the first such folder gives that file's own
 * boundary — which is the ONLY boundary that matters.
 *
 * Returns null for a file in a parent (ReTreever, rapper). Parents are apps;
 * they are allowed to reach their own code.
 */
function childRootOf(file: string, workspace: string): string | null {
	let cur = dirname(file);
	while (cur.startsWith(workspace) && cur !== workspace) {
		const parent = dirname(cur);
		if (parent === workspace && existsSync(join(cur, "lib"))) return cur;
		cur = parent;
	}
	return null;
}

export function noEscapeHatch(repoRoot: string): Plugin {
	const root = resolve(repoRoot);

	return {
		name: "rt-no-escape-hatch",

		// `enforce: "pre"`, NOT "post". THIS WAS THE BUG, and it is worth the
		// paragraph because the failure mode is total silence.
		//
		// Rollup calls resolveId hooks in order and STOPS at the first one that
		// returns a result. With "post" this plugin sat behind vite's own
		// resolver, which resolves everything — so it was never called at all.
		// MEASURED 25 Aug 2026 with a probe plugin: ZERO resolveId calls. A
		// deliberate escape built clean, exit 0, no warning anywhere.
		//
		// A guard that runs after the decision is not a guard. "pre" puts it
		// first, so it sees every specifier before anything resolves it.
		//
		// The trade: at "pre" an ALIASED import still looks like `$harness/...`
		// rather than a resolved path. That is fine — a `$`-prefixed specifier
		// is not a relative path, so it falls out at the `startsWith(".")`
		// check below and passes, which is exactly the intent: aliases are the
		// sanctioned way out.
		enforce: "pre",

		resolveId(source, importer) {
			if (!importer) return null;
			if (!source.startsWith(".")) return null; // bare specifier — a package
			if (importer.includes("node_modules")) return null;
			if (importer.startsWith("\0") || source.startsWith("\0")) return null;

			const target = resolve(importer, "..", source.split("?")[0]);

			// ── CHARGE 1: did it leave its own boundary? ─────────────────────
			//
			// THE BOUNDARY IS THE CHILD, NOT THE WORKSPACE.
			//
			// This was wrong for most of 25 Aug 2026 and the bug is worth
			// naming: the root was the workspace (fetch/), and BOTH PARENTS
			// LIVE INSIDE IT. So a child importing straight out of ReTreever
			// never "escaped" anything — the guard had nothing to say, the
			// build stayed green, and the one line the whole open-core split
			// depends on was never enforced. A fence around the farm, called a
			// fence around each pen.
			//
			// A child's legal area is ITSELF. Anything outside — a parent, a
			// sibling child, the workspace — is an escape, and the only
			// sanctioned way out is the alias, which is handled below.
			const boundary = childRootOf(importer, root) ?? root;
			const rel = relative(boundary, target);
			const escaped = rel.startsWith("..") || isAbsolute(rel);
			if (escaped && !target.includes("node_modules")) {
				const isChild = boundary !== root;
				throw new Error(
					`\n\n  ${isChild ? "A CHILD REACHED OUTSIDE ITSELF" : "RAW PATH ESCAPED THE REPO"} — build stopped.\n\n` +
						`    in:      ${relative(root, importer)}\n` +
						`    import:  ${source}\n` +
						`    lands:   ${relative(root, target)}\n` +
						`    allowed: ${relative(root, boundary) || "the repo"}/**\n\n` +
						(isChild
							? `  A child has TWO possible parents and must run under either,\n` +
								`  so it may never reach one by path. Side by side on one\n` +
								`  machine such a path RESOLVES — which is exactly why this\n` +
								`  has to stop the build rather than wait to be noticed. It\n` +
								`  resolves to nothing the moment the child is cloned alone.\n\n` +
								`  Take what you need as a PROP from the parent that mounted\n` +
								`  you, or import it from your own folder. Never by path.\n`
							: `  Leaving the repo is allowed ONLY through an alias, because\n` +
								`  an alias is one declared line somebody can review and\n` +
								`  repoint. A raw ../../ climb hardcodes today's folder layout\n` +
								`  into a source file, and it breaks silently the next time\n` +
								`  anything moves.\n\n` +
								`  Use $harness/<child>/... (svelte.config.js kit.alias), or\n` +
								`  move the file inside the repo.\n`),
				);
			}

			// ── CHARGE 2: is the spelling right? ─────────────────────────────
			if (/\.[a-z0-9]+$/i.test(target) && existsSync(target) && !exactCase(target)) {
				throw new Error(
					`\n\n  IMPORT CASE DOES NOT MATCH DISK — build stopped.\n\n` +
						`    in:     ${relative(root, importer)}\n` +
						`    import: ${source}\n\n` +
						`  This resolves on macOS ONLY because APFS is case-insensitive.\n` +
						`  Linux is not, and Linux is what the deploy builds on — so this\n` +
						`  renders perfectly on every Mac here and 404s in production.\n\n` +
						`  Fix the spelling to match the folder exactly.\n`,
				);
			}

			return null; // not ours to resolve — just watching the door
		},
	};
}
