/**
 * Offline basemap — bundled PMTiles vector source rendered as the bottom
 * layer of the map. Always on. When the Mapbox satellite/streets layers
 * are reachable they composite on top; in airplane mode this is what the
 * user sees so the screen is never black.
 *
 * Source: a single .pmtiles file shipped in `static/mobileAssets/`.
 *   - Coverage: world minus Antarctica
 *   - Zoom range: z0–z6 (state/province-level detail)
 *   - Size: ~85 MB
 *   - Generated by `scripts/fetch-basemap.sh`
 *
 * Mapbox GL JS v3.21+ auto-detects the .pmtiles extension on a vector
 * source URL — no protocol registration, no plugin required. PMTiles
 * uses HTTP range requests; Capacitor's WebView (WKWebView on iOS,
 * WebViewAssetLoader on Android) honors Range headers on bundled
 * assets so the file streams in tile-by-tile from disk.
 *
 * Styling: layer specs come from @protomaps/basemaps. We strip all
 * label/symbol layers (matches Get Cache's minimal aesthetic) and tune
 * the dark flavor to match `mapStyleNatural` so online and offline
 * basemaps share a palette.
 */
import type mapboxgl from "mapbox-gl";
import { layers, namedFlavor } from "@protomaps/basemaps";

const SOURCE_ID = "offline-basemap";
const SOURCE_LAYER_PREFIX = "pmtiles_";
const PMTILES_URL = "/mobileAssets/basemap.pmtiles";

// Match mapStyleNatural's palette so the offline floor blends with
// the online natural-dark satellite shell.
const OFFLINE_PALETTE = {
    earth: "#1a2820",
    water: "#0d2038",
    waterway: "#1a3a5a",
    boundaries: "rgba(255, 255, 255, 0.18)",
    park: "#22381f",
    wood: "#1d2e1c",
    glacier: "#2a3444",
    sand: "#3a3a2a",
} as const;

/**
 * Build a Protomaps Flavor by overriding the dark preset with our palette.
 * The Flavor type has ~80 color slots — we override the structural ones
 * and let the rest fall through to dark defaults (which we'll never see
 * since we strip labels).
 */
function buildOfflineFlavor() {
    const dark = namedFlavor("dark");
    return {
        ...dark,
        background: OFFLINE_PALETTE.earth,
        earth: OFFLINE_PALETTE.earth,
        water: OFFLINE_PALETTE.water,
        glacier: OFFLINE_PALETTE.glacier,
        sand: OFFLINE_PALETTE.sand,
        beach: OFFLINE_PALETTE.sand,
        wood_a: OFFLINE_PALETTE.wood,
        wood_b: OFFLINE_PALETTE.wood,
        park_a: OFFLINE_PALETTE.park,
        park_b: OFFLINE_PALETTE.park,
        scrub_a: OFFLINE_PALETTE.wood,
        scrub_b: OFFLINE_PALETTE.wood,
        boundaries: OFFLINE_PALETTE.boundaries,
    };
}

/**
 * Add the offline basemap source + layers under all existing layers.
 *
 * Idempotent: safe to call multiple times (e.g. after `setStyle`).
 * Failures are logged but never thrown — if the .pmtiles file is missing
 * or unreadable, the rest of the map still works.
 */
export function addOfflineBasemap(map: mapboxgl.Map): void {
    if (map.getSource(SOURCE_ID)) return;

    try {
        // Mapbox GL JS auto-detects PMTiles by the .pmtiles extension.
        // No `pmtiles://` protocol, no plugin.
        // biome-ignore lint/suspicious/noExplicitAny: cross-spec source shape
        map.addSource(SOURCE_ID, {
            type: "vector",
            url: PMTILES_URL,
        } as any);
    } catch (err) {
        console.warn("[OfflineBasemap] addSource failed:", err);
        return;
    }

    const flavor = buildOfflineFlavor();
    // labelsOnly:false → geometry layers only. We additionally strip every
    // symbol layer below so the result is purely shapes, no text, no icons.
    const allLayers = layers(SOURCE_ID, flavor, { labelsOnly: false });

    // Find the lowest existing layer so we insert beneath everything else.
    const beforeId = map.getStyle()?.layers?.[0]?.id;

    let added = 0;
    for (const spec of allLayers) {
        // Drop symbol layers (labels, POI icons) — Get Cache's minimal style.
        if (spec.type === "symbol") continue;

        // Rewrite the source-layer if Protomaps uses a prefix scheme that
        // doesn't match our PMTiles. The current Protomaps spec doesn't
        // need this, but it's a one-line guard if a future build does.
        if ("source-layer" in spec && SOURCE_LAYER_PREFIX) {
            // no-op currently; Protomaps source-layers map 1:1 to PMTiles tiles
        }

        try {
            // Rename layer ids so they don't collide with Mapbox style layers.
            const renamed = { ...spec, id: `offline-${spec.id}` };
            // biome-ignore lint/suspicious/noExplicitAny: maplibre↔mapbox spec drift
            map.addLayer(renamed as any, beforeId);
            added++;
        } catch (err) {
            // Per-layer failures are non-fatal — Mapbox warns and skips.
            console.warn(`[OfflineBasemap] addLayer ${spec.id} failed:`, err);
        }
    }

    console.log(`[OfflineBasemap] mounted (${added} layers)`);
}

/**
 * Remove the offline basemap (source + all `offline-*` layers).
 * Useful for style switches that re-add the basemap fresh.
 */
export function removeOfflineBasemap(map: mapboxgl.Map): void {
    const style = map.getStyle();
    if (!style) return;
    for (const layer of style.layers ?? []) {
        if (layer.id.startsWith("offline-")) {
            try {
                map.removeLayer(layer.id);
            } catch {
                /* ignore */
            }
        }
    }
    if (map.getSource(SOURCE_ID)) {
        try {
            map.removeSource(SOURCE_ID);
        } catch {
            /* ignore */
        }
    }
}
